#Docker compose file for postgres

version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

#  Prometheus
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
    - db

#  Grafana
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    depends_on:
    - prometheus
    volumes:
      - ./grafana-storage:/var/lib/grafana

volumes:
    db-data: